apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: dop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: satyamuralidhar/kafka-manager:latest

        ports:
        - containerPort: 80
        env:
        - name: zk_host
          value: zookeeper.dop:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: dop
spec:
  selector:
    app: kafka-manager
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31015